import {describe,it,expect} from 'vitest';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {applyGeneratedResponse,generatedResponses,latestNewResponse,parseAllowedNpmCommand,writeGeneratedFiles} from '../src/simpleDeepSeek.js';

describe('simple DeepSeek output',()=>{
 it('writes parsed content exactly as UTF-8',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fa-exact-')),content='/** test */\nconst x = `hello ${name}`;\n// comment\n/* block */\nПривет ✓',response=generatedResponses(JSON.stringify({files:[{path:'exact.js',content}]})).at(-1)!;await writeGeneratedFiles(root,response.files);expect(await fs.readFile(path.join(root,'exact.js'))).toEqual(Buffer.from(content,'utf8'))});
 it('creates nested parent directories',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fa-nested-'));await writeGeneratedFiles(root,[{path:'src/components/Test.js',content:'export default true'}]);expect(await fs.readFile(path.join(root,'src/components/Test.js'),'utf8')).toBe('export default true')});
 it('keeps files-only JSON backward compatible',()=>{const responses=generatedResponses('{"files":[{"path":"index.html","content":"hello"}]}');expect(responses.at(-1)).toEqual({files:[{path:'index.html',content:'hello'}],commands:[]})});
 it('does not reuse old assistant responses',()=>{const old='{"files":[{"path":"index.html","content":"old"}]}',newFiles=Array.from({length:5},(_,i)=>({path:`src/file${i}.js`,content:`file ${i}`})),newText=JSON.stringify({files:newFiles,commands:['npm install','npm run build']});expect(latestNewResponse([old],1)).toBeNull();expect(latestNewResponse([old,newText],1)).toEqual({files:newFiles,commands:['npm install','npm run build']})});
 it('rejects unsafe paths and commands',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fa-unsafe-'));await expect(writeGeneratedFiles(root,[{path:'../escape.js',content:'no'}])).rejects.toThrow('escapes project root');expect(()=>parseAllowedNpmCommand('npm run build && whoami')).toThrow('Unsafe command rejected')});
 it('repairs a failed build and retries it',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fa-repair-'));let runs=0,repairs=0;const result=await applyGeneratedResponse(root,{files:[{path:'src/value.js',content:'broken'}],commands:['npm run build']},async failure=>{repairs++;expect(failure).toMatchObject({command:'npm run build',exitCode:1,output:'build error'});return {files:[{path:'src/value.js',content:'fixed'}],commands:[]}},async()=>{runs++;if(runs===1)throw Object.assign(new Error('failed'),{command:'npm run build',exitCode:1,output:'build error'})});expect(await fs.readFile(path.join(root,'src/value.js'),'utf8')).toBe('fixed');expect({runs,repairs,result}).toEqual({runs:2,repairs:1,result:{filesCreated:1,commandsPassed:1,repairAttempts:1}})});
 it('stops after two failed repair attempts',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fa-repair-stop-'));let runs=0,repairs=0;const work=applyGeneratedResponse(root,{files:[{path:'index.js',content:'broken'}],commands:['npm run build']},async()=>{repairs++;return {files:[{path:'index.js',content:`repair ${repairs}`}],commands:[]}},async()=>{runs++;throw Object.assign(new Error('failed'),{command:'npm run build',exitCode:1,output:'still broken'})});await expect(work).rejects.toMatchObject({command:'npm run build',exitCode:1,repairAttempts:2});expect({runs,repairs}).toEqual({runs:3,repairs:2})});
});
