import fs from 'node:fs/promises'; import path from 'node:path'; import crypto from 'node:crypto'; import {ensureAppDir,projectId} from './config.js';
interface Entry{relative:string;existed:boolean;backup?:string}
export class Snapshot { private entries=new Map<string,Entry>(); constructor(public root:string,public id:string,public dir:string){}
 static async create(root:string,id:string=crypto.randomUUID()){const dir=path.join(await ensureAppDir(),'snapshots',projectId(root),id);await fs.mkdir(path.join(dir,'files'),{recursive:true});return new Snapshot(path.resolve(root),id,dir)}
 async capture(relative:string){if(this.entries.has(relative))return;const target=path.join(this.root,relative);let e:Entry={relative,existed:false};try{const st=await fs.stat(target);if(st.isDirectory())throw new Error('Recursive directory actions are not supported');const backup=crypto.createHash('sha256').update(relative).digest('hex');await fs.copyFile(target,path.join(this.dir,'files',backup));e={relative,existed:true,backup};}catch(x:any){if(x.code!=='ENOENT')throw x;}this.entries.set(relative,e);await this.save();}
 async save(){await fs.writeFile(path.join(this.dir,'journal.json'),JSON.stringify({id:this.id,root:this.root,entries:[...this.entries.values()]},null,2))}
 async rollback(){for(const e of [...this.entries.values()].reverse()){const target=path.join(this.root,e.relative);if(e.existed){await fs.mkdir(path.dirname(target),{recursive:true});await fs.copyFile(path.join(this.dir,'files',e.backup!),target)}else await fs.rm(target,{force:true});}}
}
export async function rollbackLatest(root:string){const base=path.join(await ensureAppDir(),'snapshots',projectId(root));const dirs=await fs.readdir(base).catch(()=>[]);if(!dirs.length)throw new Error('No snapshot found');const records=await Promise.all(dirs.map(async d=>({d,t:(await fs.stat(path.join(base,d))).mtimeMs})));const dir=path.join(base,records.sort((a,b)=>b.t-a.t)[0].d);const j=JSON.parse(await fs.readFile(path.join(dir,'journal.json'),'utf8'));const s=new Snapshot(j.root,j.id,dir);for(const e of j.entries)s['entries'].set(e.relative,e);await s.rollback();}
